import { motion } from 'framer-motion';
import { mockAIRecommendation } from '../../data/mockData';
import { Bot, TrendingUp, TrendingDown, Minus, BookOpen, Target, Sparkles, ChevronRight, BrainCircuit } from 'lucide-react';

const container = { hidden: { opacity: 0 }, show: { opacity: 1, transition: { staggerChildren: 0.1 } } };
const item = { hidden: { opacity: 0, y: 20 }, show: { opacity: 1, y: 0 } };

function TopicStrength({ topic, score, status }) {
  const config = {
    'Needs Improvement': { color: '#ef4444', icon: TrendingDown, bg: 'bg-red-500/10', textColor: 'text-red-400' },
    'Good': { color: '#f59e0b', icon: Minus, bg: 'bg-amber-500/10', textColor: 'text-amber-400' },
    'Strong': { color: '#22c55e', icon: TrendingUp, bg: 'bg-green-500/10', textColor: 'text-green-400' },
  };
  const c = config[status];

  return (
    <div className="flex items-center gap-3 p-3 rounded-lg bg-secondary/50">
      <div className={`w-10 h-10 rounded-lg ${c.bg} flex items-center justify-center`}>
        <c.icon className={`w-5 h-5 ${c.textColor}`} />
      </div>
      <div className="flex-1">
        <p className="text-sm font-medium">{topic}</p>
        <p className={`text-xs ${c.textColor}`}>{status}</p>
      </div>
      <div className="text-right">
        <p className="text-lg font-bold" style={{ color: c.color }}>{score}%</p>
      </div>
    </div>
  );
}

export default function AIMentorPage() {
  const rec = mockAIRecommendation;

  return (
    <motion.div variants={container} initial="hidden" animate="show" className="space-y-6 max-w-4xl mx-auto">
      <motion.div variants={item}>
        <h1 className="text-2xl font-bold flex items-center gap-2">
          <BrainCircuit className="w-6 h-6 text-eco-purple" /> AI Eco Mentor
        </h1>
        <p className="text-sm text-muted-foreground mt-1">Personalized learning recommendations based on your performance</p>
      </motion.div>

      {/* AI Notice */}
      <motion.div variants={item} className="p-4 rounded-xl bg-eco-purple/5 border border-eco-purple/20 flex items-start gap-3">
        <Sparkles className="w-5 h-5 text-eco-purple shrink-0 mt-0.5" />
        <div>
          <p className="text-sm font-medium text-eco-purple">AI-Powered Recommendations</p>
          <p className="text-xs text-muted-foreground mt-1">These recommendations are generated by analyzing your quiz performance, topic accuracy, lesson completion, and mission activity.</p>
        </div>
      </motion.div>

      {/* Personalized Learning Path */}
      <motion.div variants={item} className="glass rounded-xl p-6">
        <h2 className="text-lg font-semibold mb-4 flex items-center gap-2">
          <Bot className="w-5 h-5 text-eco-teal" /> Your Personalized Learning Path
        </h2>

        {rec.weakTopics.length > 0 && (
          <div className="mb-4">
            <p className="text-xs uppercase tracking-wider text-destructive font-medium mb-2">Needs Improvement</p>
            <div className="space-y-2">
              {rec.weakTopics.map(t => <TopicStrength key={t.topic} {...t} />)}
            </div>
          </div>
        )}

        {rec.goodTopics.length > 0 && (
          <div className="mb-4">
            <p className="text-xs uppercase tracking-wider text-eco-amber font-medium mb-2">Good</p>
            <div className="space-y-2">
              {rec.goodTopics.map(t => <TopicStrength key={t.topic} {...t} />)}
            </div>
          </div>
        )}

        {rec.strongTopics.length > 0 && (
          <div>
            <p className="text-xs uppercase tracking-wider text-eco-green font-medium mb-2">Strong</p>
            <div className="space-y-2">
              {rec.strongTopics.map(t => <TopicStrength key={t.topic} {...t} />)}
            </div>
          </div>
        )}
      </motion.div>

      {/* Recommended Lesson */}
      <motion.div variants={item} className="glass rounded-xl p-6 border-l-4 border-eco-blue">
        <div className="flex items-start gap-3">
          <div className="w-12 h-12 rounded-xl bg-eco-blue/10 flex items-center justify-center shrink-0">
            <BookOpen className="w-6 h-6 text-eco-blue" />
          </div>
          <div className="flex-1">
            <p className="text-xs text-eco-blue font-medium mb-1">Recommended Next Lesson</p>
            <h3 className="text-lg font-semibold">{rec.recommendedLesson.title}</h3>
            <p className="text-sm text-muted-foreground mt-1">"{rec.recommendedLesson.reason}"</p>
            <motion.button whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }}
              className="mt-3 px-5 py-2.5 rounded-xl gradient-primary text-white text-sm font-semibold flex items-center gap-2">
              Start Recommended Lesson <ChevronRight className="w-4 h-4" />
            </motion.button>
          </div>
        </div>
      </motion.div>

      {/* Recommended Mission */}
      <motion.div variants={item} className="glass rounded-xl p-6 border-l-4 border-eco-green">
        <div className="flex items-start gap-3">
          <div className="w-12 h-12 rounded-xl bg-eco-green/10 flex items-center justify-center shrink-0">
            <Target className="w-6 h-6 text-eco-green" />
          </div>
          <div className="flex-1">
            <p className="text-xs text-eco-green font-medium mb-1">AI Recommendation</p>
            <h3 className="text-lg font-semibold">{rec.recommendedMission.title}</h3>
            <p className="text-sm text-muted-foreground mt-1">"{rec.recommendedMission.reason}"</p>
            <motion.button whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }}
              className="mt-3 px-5 py-2.5 rounded-xl bg-eco-green/10 text-eco-green text-sm font-semibold flex items-center gap-2 hover:bg-eco-green/20">
              Start Mission <ChevronRight className="w-4 h-4" />
            </motion.button>
          </div>
        </div>
      </motion.div>

      {/* Learning Style Insight */}
      <motion.div variants={item} className="glass rounded-xl p-5">
        <h3 className="font-semibold mb-3 flex items-center gap-2">
          <Sparkles className="w-5 h-5 text-eco-amber" /> Learning Style Analysis
        </h3>
        <div className="grid sm:grid-cols-3 gap-3">
          <div className="p-3 rounded-lg bg-secondary/50 text-center">
            <p className="text-2xl mb-1">📊</p>
            <p className="text-xs font-medium">Scenario-Based</p>
            <p className="text-xs text-eco-green mt-1">Best Performance</p>
          </div>
          <div className="p-3 rounded-lg bg-secondary/50 text-center">
            <p className="text-2xl mb-1">🎯</p>
            <p className="text-xs font-medium">Mission-Based</p>
            <p className="text-xs text-eco-amber mt-1">High Engagement</p>
          </div>
          <div className="p-3 rounded-lg bg-secondary/50 text-center">
            <p className="text-2xl mb-1">📖</p>
            <p className="text-xs font-medium">Reading</p>
            <p className="text-xs text-muted-foreground mt-1">Moderate</p>
          </div>
        </div>
      </motion.div>
    </motion.div>
  );
}
