import { motion } from 'framer-motion';
import { mockAIInsights } from '../../data/mockData';
import { Brain, Sparkles, TrendingUp, AlertTriangle, Lightbulb, Target, Star } from 'lucide-react';

const container = { hidden: { opacity: 0 }, show: { opacity: 1, transition: { staggerChildren: 0.1 } } };
const item = { hidden: { opacity: 0, y: 20 }, show: { opacity: 1, y: 0 } };

const typeConfig = {
  observation: { color: 'border-eco-blue', bg: 'bg-eco-blue/5', icon: TrendingUp, iconColor: 'text-eco-blue' },
  warning: { color: 'border-eco-amber', bg: 'bg-eco-amber/5', icon: AlertTriangle, iconColor: 'text-eco-amber' },
  insight: { color: 'border-eco-teal', bg: 'bg-eco-teal/5', icon: Lightbulb, iconColor: 'text-eco-teal' },
  recommendation: { color: 'border-eco-green', bg: 'bg-eco-green/5', icon: Target, iconColor: 'text-eco-green' },
  positive: { color: 'border-eco-gold', bg: 'bg-eco-gold/5', icon: Star, iconColor: 'text-eco-gold' },
};

export default function InsightsPage() {
  return (
    <motion.div variants={container} initial="hidden" animate="show" className="space-y-6 max-w-4xl mx-auto">
      <motion.div variants={item}>
        <h1 className="text-2xl font-bold flex items-center gap-2"><Brain className="w-6 h-6 text-eco-purple" /> AI Class Insights</h1>
        <p className="text-sm text-muted-foreground mt-1">AI-generated insights based on student performance data</p>
      </motion.div>

      <motion.div variants={item} className="p-4 rounded-xl bg-eco-purple/5 border border-eco-purple/20 flex items-start gap-3">
        <Sparkles className="w-5 h-5 text-eco-purple shrink-0 mt-0.5" />
        <div>
          <p className="text-sm font-medium text-eco-purple">AI-Generated Insights</p>
          <p className="text-xs text-muted-foreground mt-1">These insights are generated by analyzing class-wide performance data, quiz results, mission completions, and learning patterns. They are meant to assist your teaching decisions.</p>
        </div>
      </motion.div>

      <motion.div variants={container} className="space-y-4">
        {mockAIInsights.map((insight, i) => {
          const config = typeConfig[insight.type];
          return (
            <motion.div key={i} variants={item}
              className={`glass rounded-xl p-5 border-l-4 ${config.color} ${config.bg}`}>
              <div className="flex items-start gap-3">
                <div className={`w-10 h-10 rounded-xl ${config.bg} flex items-center justify-center shrink-0`}>
                  <config.icon className={`w-5 h-5 ${config.iconColor}`} />
                </div>
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-1">
                    <span className={`text-xs font-medium uppercase tracking-wider ${config.iconColor}`}>{insight.type}</span>
                    {insight.priority === 'high' && (
                      <span className="text-[10px] px-1.5 py-0.5 rounded-full bg-destructive/10 text-destructive">High Priority</span>
                    )}
                  </div>
                  <p className="text-sm">{insight.text}</p>
                </div>
                <span className="text-xl shrink-0">{insight.icon}</span>
              </div>
            </motion.div>
          );
        })}
      </motion.div>

      {/* Recommended Action */}
      <motion.div variants={item} className="glass rounded-xl p-6 border-2 border-eco-green/20">
        <h3 className="font-semibold mb-3 flex items-center gap-2">
          <Target className="w-5 h-5 text-eco-green" /> Recommended Action
        </h3>
        <p className="text-sm text-muted-foreground mb-4">Based on the insights above, the AI recommends the following action:</p>
        <div className="p-4 rounded-xl gradient-primary/10 bg-eco-green/5">
          <p className="text-sm font-medium">Assign Waste Segregation Mission to Class 8-A</p>
          <p className="text-xs text-muted-foreground mt-1">This will help improve the weak topic scores in Waste Management, which is currently the lowest-performing topic in the class.</p>
        </div>
        <motion.button whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }}
          className="mt-4 px-5 py-2.5 rounded-xl bg-gradient-to-r from-blue-500 to-indigo-600 text-white text-sm font-semibold">
          Apply Recommendation
        </motion.button>
      </motion.div>

      {/* Summary Stats */}
      <motion.div variants={item} className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        {[
          { label: 'Strong Topics', value: '3', color: 'text-eco-green', emoji: '💪' },
          { label: 'Weak Topics', value: '2', color: 'text-destructive', emoji: '⚠️' },
          { label: 'Completion Rate', value: '77%', color: 'text-eco-blue', emoji: '📊' },
          { label: 'Engagement', value: 'High', color: 'text-eco-amber', emoji: '🔥' },
        ].map(stat => (
          <div key={stat.label} className="glass rounded-xl p-3 text-center">
            <span className="text-2xl">{stat.emoji}</span>
            <p className={`text-lg font-bold ${stat.color}`}>{stat.value}</p>
            <p className="text-[10px] text-muted-foreground">{stat.label}</p>
          </div>
        ))}
      </motion.div>
    </motion.div>
  );
}
